services:
  ollama:
    image: ollama/ollama:0.5.7
    container_name: ollama
    volumes:
      - ollama_vol:/root/.ollama
    ports:
      - 11434:11434
    pull_policy: always
    tty: true
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - llm-agent

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_vol:/qdrant/storage
    environment:
      - QDRANT_STORAGE_PATH=/qdrant/storage
    restart: unless-stopped
    networks:
      - llm-agent

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.3
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_vol:/var/lib/weaviate
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
      OPENAI_APIKEY: 'ollama'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
    networks:
      - llm-agent

  postgres:
    image: postgres:12
    container_name: postgres
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    restart: unless-stopped  
    networks:
      - llm-agent

volumes:
  ollama_vol:
    external: false
  qdrant_vol:
    external: false
  postgres_vol:
    external: false
  weaviate_vol:
    external: false

networks:
  llm-agent:
    external: false